apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: jenkins
  labels:
    role: jenkins-agent
spec:
  containers:
    - name: agent
      image: ubuntu:22.04
      command: [ "sleep" ]
      args: [ "infinity" ]